In [8]:
# Importing necessary helpful libiraries
import numpy as np
import pandas as pd

# File Reading and Setup

### Instructions 
Setting up the file, put string of raw data into csv


Ex. 

rawData = pd.read_csv('dummy.csv')

In [9]:
rawData = pd.read_csv('SK20220224.csv', sep = ";")
rawData.tail(1)

,Sample ID,Analyte Name,Int (Corr),RSD (Corr Int),SD (Corr Int),Conc (Calib),Conc (Samp),RSD (Conc),SD (Calib),SD (Samp),...,Conc (Samp)2,Repl No3,Conc (Calib)3,Conc (Samp)3,Repl No4,Conc (Calib)4,Conc (Samp)4,Repl No5,Conc (Calib)5,Conc (Samp)5
1376,blank,Zr 343.823,-70.93090155,37.82508887,26.82967655,0.0009045791051,,24.24383747,0.000219304688,,...,,3,0.001156953387,,NaN,NaN,NaN,NaN,NaN,NaN

### Check if table is in the correct format

In [11]:
rawData.tail(40)

,Sample ID,Analyte Name,Int (Corr),RSD (Corr Int),SD (Corr Int),Conc (Calib),Conc (Samp),RSD (Conc),SD (Calib),SD (Samp),...,Conc (Samp)2,Repl No3,Conc (Calib)3,Conc (Samp)3,Repl No4,Conc (Calib)4,Conc (Samp)4,Repl No5,Conc (Calib)5,Conc (Samp)5
1337,blank,In 230.606,14.8887978,27.52423764,4.098028089,0.005136994559,,21.11600132,0.001084727839,,...,,3,0.006153778718,,NaN,NaN,NaN,NaN,NaN,NaN
1338,blank,Ir 208.882,5682.787082,6.129632458,348.3339615,2.291509034,,6.059849306,0.1388619943,,...,,3,2.155381658,,NaN,NaN,NaN,NaN,NaN,NaN
1339,blank,K 766.490,-3079.424822,19.91935144,613.4014528,-0.005752172976,,29.89452096,0.001719584556,,...,,3,-0.006912771548,,NaN,NaN,NaN,NaN,NaN,NaN
1340,blank,La 408.672,-387.468367,19.17254826,74.28755966,-0.002416170075,,27.3525836,0.0006608849395,,...,,3,-0.00256719401,,NaN,NaN,NaN,NaN,NaN,NaN
1341,blank,Li 670.784,-294990.0337,1.384291834,4083.522947,-0.01530475882,,1.395304511,0.0002135479902,,...,,3,-0.01546339844,,NaN,NaN,NaN,NaN,NaN,NaN
1342,blank,Li 610.362,-759.7287609,33.48367795,254.3851316,9.901963287e-005,,786.6020122,0.0007788904246,,...,,3,-0.0006175950112,,NaN,NaN,NaN,NaN,NaN,NaN
1343,blank,Lu 261.542,14.20321715,6.210503255,0.8820912632,0.0004085472453,,0.9524787087,3.891325526e-006,,...,,3,0.0004061935911,,NaN,NaN,NaN,NaN,NaN,NaN
1344,blank,Mg 285.213,-236.1238903,5.001182646,11.80898702,-0.001004480639,,12.18693716,0.0001224154242,,...,,3,-0.0008702306691,,NaN,NaN,NaN,NaN,NaN,NaN
1345,blank,Mn 257.610,-340.4650167,4.972091024,16.92823054,-0.00068734001,,6.271043209,4.310338902e-005,,...,,3,-0.0007172030602,,NaN,NaN,NaN,NaN,NaN,NaN
1346,blank,Mo 202.031,0.7149862917,477.3105242,3.412704817,0.0001996074677,,190.5298014,0.0003803117118,,...,,3,-0.0002249920289,,NaN,NaN,NaN,NaN,NaN,NaN
1347,blank,Na 589.592,-7844.162575,16.4388103,1289.487005,-0.01031890315,,25.27220734,0.002607814599,,...,,3,-0.01243361486,,NaN,NaN,NaN,NaN,NaN,NaN
1348,blank,Nb 309.418,1153.443456,0.6930387569,7.993810189,0.02545481715,,0.5169915528,0.0001315992545,,...,,3,0.02557052281,,NaN,NaN,NaN,NaN,NaN,NaN
1349,blank,Nd 430.358,-46.34929762,10.60497778,4.915332716,-0.001076248202,,8.257737282,8.8873749e-005,,...,,3,-0.001040844063,,NaN,NaN,NaN,NaN,NaN,NaN
1350,blank,Ni 231.604,-9.257584908,81.68560853,7.562114567,-0.0004795202623,,118.0669381,0.0005661548911,,...,,3,-0.0003833368672,,NaN,NaN,NaN,NaN,NaN,NaN
1351,blank,Os 228.226,-3.802040914,212.0993546,8.06410424,-0.002807757126,,25.40341945,0.0007132663197,,...,,3,-0.003587619861,,NaN,NaN,NaN,NaN,NaN,NaN
1352,blank,P 213.617,-56.92024492,10.84491491,6.17295213,-0.009223425807,,9.839825518,0.0009075690062,,...,,3,-0.008367924389,,NaN,NaN,NaN,NaN,NaN,NaN
1353,blank,Pb 220.353,9.471889257,14.9552252,1.416542369,0.00232537987,,11.39720266,0.0002650282564,,...,,3,0.002019626984,,NaN,NaN,NaN,NaN,NaN,NaN
1354,blank,Pd 340.458,24.77849085,1.819917935,0.4509481989,0.004260315236,,0.7458025754,3.177354074e-005,,...,,3,0.00427653838,,NaN,NaN,NaN,NaN,NaN,NaN
1355,blank,Pr 390.844,41.06787326,54.89113058,22.54261994,0.002991006571,,23.92153659,0.0007154947313,,...,,3,0.002555528904,,NaN,NaN,NaN,NaN,NaN,NaN
1356,blank,Pt 265.945,60.3702953,3.193655396,1.928019193,0.01618405056,,2.682941746,0.0004342086487,,...,,3,0.01643975094,,NaN,NaN,NaN,NaN,NaN,NaN
1357,blank,Rh 343.489,84.28181787,17.17605638,14.47629256,0.007013906328,,13.21874785,0.0009271505922,,...,,3,0.006008084667,,NaN,NaN,NaN,NaN,NaN,NaN
1358,blank,Ru 240.272,25.01469404,34.89757058,8.729520508,0.002526386661,,23.89134406,0.0006035877297,,...,,3,0.003051472979,,NaN,NaN,NaN,NaN,NaN,NaN
1359,blank,Sb 217.582,7.286801115,33.12650489,2.413862528,0.005212610127,,29.62001695,0.001543976003,,...,,3,0.006993778569,,NaN,NaN,NaN,NaN,NaN,NaN
1360,blank,Se 196.026,8.501830328,33.79636626,2.873309717,0.005577575452,,44.57018901,0.002485935921,,...,,3,0.005879116477,,NaN,NaN,NaN,NaN,NaN,NaN
1361,blank,Si 251.611,-305.6909233,3.475572678,10.62451021,-0.009283398021,,4.731090641,0.0004392059749,,...,,3,-0.00971067578,,NaN,NaN,NaN,NaN,NaN,NaN
1362,blank,Sm 359.260,85.29153416,57.2585455,48.83669189,0.003019368458,,47.50317416,0.001434295857,,...,,3,0.00138281319,,NaN,NaN,NaN,NaN,NaN,NaN
1363,blank,Sn 189.927,-18.48786667,3.62157989,0.6695528614,-0.003736754638,,4.670235722,0.00017451525,,...,,3,-0.003827727302,,NaN,NaN,NaN,NaN,NaN,NaN
1364,blank,Sr 407.771,-410.0167874,2.710081022,11.11178714,0.0007334424763,,0.5152915827,3.779367344e-006,,...,,3,0.0007369105431,,NaN,NaN,NaN,NaN,NaN,NaN
1365,blank,Ta 226.230,13.54772515,48.25644284,6.537650245,0.01001830729,,13.61317241,0.001363809444,,...,,3,0.009035501773,,NaN,NaN,NaN,NaN,NaN,NaN
1366,blank,Te 238.578,-17.71857048,61.9922595,10.98414219,-0.02947574101,,83.6139028,0.02464581744,,...,,3,-0.02901016468,,NaN,NaN,NaN,NaN,NaN,NaN
1367,blank,Th 283.730,74.77287033,7.191135852,5.377018686,0.007756347425,,5.408882078,0.0004195316858,,...,,3,0.008236254272,,NaN,NaN,NaN,NaN,NaN,NaN
1368,blank,Ti 334.940,-588.3282468,13.19323004,77.61949898,-0.001329842947,,18.32568563,0.0002437028378,,...,,3,-0.001131347521,,NaN,NaN,NaN,NaN,NaN,NaN
1369,blank,Ti 336.121,256607.0595,3.034138526,7785.813652,1.186422277,,2.946396968,0.03495670999,,...,,3,1.220788456,,NaN,NaN,NaN,NaN,NaN,NaN
1370,blank,Tm 346.220,460.0486463,1.355148344,6.234341612,0.008088936185,,1.301551811,0.0001052816954,,...,,3,0.008184765866,,NaN,NaN,NaN,NaN,NaN,NaN
1371,blank,V 290.880,-1186.319312,0.5514873194,6.542400574,-0.02603579228,,0.561677425,0.0001462371676,,...,,3,-0.02612978025,,NaN,NaN,NaN,NaN,NaN,NaN
1372,blank,W 207.912,-16.95499469,36.75028139,6.231008257,-0.002670249524,,51.27596863,0.001369196308,,...,,3,-0.002857868617,,NaN,NaN,NaN,NaN,NaN,NaN
1373,blank,Y 371.029,-61.9366958,9.098942674,5.635584445,0.0001357642703,,9.92449834,1.347392275e-005,,...,,3,0.0001372944593,,NaN,NaN,NaN,NaN,NaN,NaN
1374,blank,Yb 328.937,-86.91315136,43.32239524,37.65285895,0.00132971571,,2.612793265,3.474272252e-005,,...,,3,0.001331886349,,NaN,NaN,NaN,NaN,NaN,NaN
1375,blank,Zn 206.200,-205.6231792,1.495600251,3.075300785,-0.01104790899,,0.997148702,0.0001101640811,,...,,3,-0.01105103722,,NaN,NaN,NaN,NaN,NaN,NaN
1376,blank,Zr 343.823,-70.93090155,37.82508887,26.82967655,0.0009045791051,,24.24383747,0.000219304688,,...,,3,0.001156953387,,NaN,NaN,NaN,NaN,NaN,NaN

### Doing Step 2 for Data workup: 


### Initialized a new table called step2Table, indexed by Sample ID and Analyte name. The following code converts the columns into necessary datatype, and calculating the standard deviation while appending it to the table

*** TO BE FIXED:
    Currently only works for samples with 3 trials
    Potential roundoff eorror when taking the sqrt, very unlikely

In [4]:
step2Table = pd.DataFrame({"Sample ID"   : rawData['Sample ID'],
                           "AnalyteName" : rawData['Analyte Name'],
                           "Conc (Calib)1": rawData['Conc (Calib)'],
                           "Conc (Calib)2": rawData['Conc (Calib)2'],
                           "Conc (Calib)3": rawData['Conc (Calib)3'],
                          })
step2Table = step2Table.fillna(value = 0.0)
step2Table = step2Table.replace(" ", 0.0)
step2Table = step2Table.set_index(["Sample ID", "AnalyteName"])
#May cause some sort of Roundoff Error
step2Table["Conc (Calib)1"] = step2Table["Conc (Calib)1"].astype(float)
step2Table = step2Table.astype({"Conc (Calib)1": 'float',
                                "Conc (Calib)2": 'float',
                                "Conc (Calib)3": 'float',
})
step2Table['sum'] = step2Table.sum(axis = 1)
step2Table = step2Table[step2Table['sum'] != 0]
step2Table = step2Table.drop(columns = 'sum')
std = step2Table.std(axis = 1)
avg = step2Table.mean(axis = 1)

step2Table['Average Conc Calib (mg/l)'] = avg
step2Table['Std Dev (mg/l)'] = std 
step2Table.tail(40)

                       Conc (Calib)1  Conc (Calib)2  Conc (Calib)3  \
Sample ID AnalyteName
blank     In 230.606        0.005137       0.003995       0.006154
          Ir 208.882        2.291509       2.286193       2.155382
          K 766.490        -0.005752      -0.006567      -0.006913
          La 408.672       -0.002416      -0.002988      -0.002567
          Li 670.784       -0.015305      -0.015389      -0.015463
          Li 610.362        0.000099      -0.000013      -0.000618
          Lu 261.542        0.000409       0.000406       0.000406
          Mg 285.213       -0.001004      -0.001110      -0.000870
          Mn 257.610       -0.000687      -0.000707      -0.000717
          Mo 202.031        0.000200       0.000509      -0.000225
          Na 589.592       -0.010319      -0.011118      -0.012434
          Nb 309.418        0.025455       0.025482       0.025571
          Nd 430.358       -0.001076      -0.001011      -0.001041
          Ni 231.604       -0.000480      -0.001088      -0.000383
          Os 228.226       -0.002808      -0.002647      -0.003588
          P 213.617        -0.009223      -0.009127      -0.008368
          Pb 220.353        0.002325       0.002489       0.002020
          Pd 340.458        0.004260       0.004224       0.004277
          Pr 390.844        0.002991       0.002601       0.002556
          Pt 265.945        0.016184       0.016430       0.016440
          Rh 343.489        0.007014       0.007834       0.006008
          Ru 240.272        0.002526       0.002661       0.003051
          Sb 217.582        0.005213       0.004255       0.006994
          Se 196.026        0.005578       0.002955       0.005879
          Si 251.611       -0.009283      -0.009306      -0.009711
          Sm 359.260        0.003019       0.004058       0.001383
          Sn 189.927       -0.003737      -0.003536      -0.003828
          Sr 407.771        0.000733       0.000729       0.000737
          Ta 226.230        0.010018       0.009444       0.009036
          Te 238.578       -0.029476      -0.005066      -0.029010
          Th 283.730        0.007756       0.007574       0.008236
          Ti 334.940       -0.001330      -0.001602      -0.001131
          Ti 336.121        1.186422       1.187575       1.220788
          Tm 346.220        0.008089       0.007976       0.008185
          V 290.880        -0.026036      -0.026110      -0.026130
          W 207.912        -0.002670      -0.001217      -0.002858
          Y 371.029         0.000136       0.000122       0.000137
          Yb 328.937        0.001330       0.001294       0.001332
          Zn 206.200       -0.011048      -0.010936      -0.011051
          Zr 343.823        0.000905       0.000760       0.001157

                       Average Conc Calib (mg/l)  Std Dev (mg/l)
Sample ID AnalyteName
blank     In 230.606                    0.005095        0.001080
          Ir 208.882                    2.244361        0.077104
          K 766.490                    -0.006411        0.000596
          La 408.672                   -0.002657        0.000297
          Li 670.784                   -0.015386        0.000079
          Li 610.362                   -0.000177        0.000385
          Lu 261.542                    0.000407        0.000001
          Mg 285.213                   -0.000995        0.000120
          Mn 257.610                   -0.000704        0.000015
          Mo 202.031                    0.000161        0.000368
          Na 589.592                   -0.011290        0.001068
          Nb 309.418                    0.025503        0.000060
          Nd 430.358                   -0.001043        0.000033
          Ni 231.604                   -0.000650        0.000382
          Os 228.226                   -0.003014        0.000503
          P 213.617                    -0.008906        0.000469
          Pb 220.353                    0.002278        0.000238
          Pd 340.458                    0.004254        0.000027
          Pr 390.844                    0.002716        0.000239
          Pt 265.945                    0.016351        0.000145
          Rh 343.489                    0.006952        0.000915
          Ru 240.272                    0.002746        0.000273
          Sb 217.582                    0.005487        0.001390
          Se 196.026                    0.004804        0.001608
          Si 251.611                   -0.009433        0.000240
          Sm 359.260                    0.002820        0.001349
          Sn 189.927                   -0.003700        0.000150
          Sr 407.771                    0.000733        0.000004
          Ta 226.230                    0.009499        0.000494
          Te 238.578                   -0.021184        0.013961
          Th 283.730                    0.007855        0.000342
          Ti 334.940                   -0.001354        0.000236
          Ti 336.121                    1.198262        0.019517
          Tm 346.220                    0.008083        0.000104
          V 290.880                    -0.026092        0.000050
          W 207.912                    -0.002248        0.000898
          Y 371.029                     0.000132        0.000009
          Yb 328.937                    0.001319        0.000021
          Zn 206.200                   -0.011012        0.000065
          Zr 343.823                    0.000941        0.000201

### This Chunk of code is calculating the SD and adding it to the last column, as well as removing the Analytes with no value

### STEP 3: rearangement

In [5]:
step2Table.drop(columns = ['Conc (Calib)1', 'Conc (Calib)2', 'Conc (Calib)3', ])

                       Average Conc Calib (mg/l)  Std Dev (mg/l)
Sample ID AnalyteName
hstd      Sc 361.383                  100.878060        0.855908
blank     Sc 361.383                  100.917154        1.196285
          Al 396.153                    0.003072        0.000633
          Ag 328.068                    0.011177        0.000574
          As 188.979                   -0.001198        0.000101
...                                          ...             ...
          W 207.912                    -0.002248        0.000898
          Y 371.029                     0.000132        0.000009
          Yb 328.937                    0.001319        0.000021
          Zn 206.200                   -0.011012        0.000065
          Zr 343.823                    0.000941        0.000201

[1033 rows x 2 columns]

### STEP 4: Conver Average Concentration of the element in the sample and the std dwv to (mg/kg)

Note : These are not user input data, but rather, some user defined value that are waiting to be inputted


Proposal: Creating a table similar to the one in Excel Page, convert into dictionary and access the value through there

In [6]:
# This part reqires user input which construcsts a table showing the dilution factos 


def dilution_input(dilution_ID, initial_sample_ID, eLab_sample_ID, mass_sample, volume_digestion, conc,
                   aliquote, volume_dilution, conc_dilution, dilution_factor):    
    
    dilu_Table = pd.DataFrame({'dilution ID': dilution_ID, 
                              'initial sample ID': initial_sample_ID, 
                              'eLab sample ID':eLab_sample_ID, 
                              'mass sample (g)':mass_sample, 
                              'volume digestion (ml)': volume_digestion, 
                              'conc(mg/ml)': conc,  
                              'aliquote(ml)': aliquote, 
                              'volume dilution(ml)': volume_dilution,
                              'conc dilution': conc_dilution,
                              'dilution_factor': dilution_factor})
            
    return dilu_Table



#Question for Thursday:
  #  1. Is this way of data inputting optimal, if not, generating a new csv file would work too.
   # 2. Application of step 4 formula clarification. Not sure which element to use.

In [7]:
dilution_ID = np.array(['test1', 'test2'], dtype = str)
#initial_sample_ID = np.array(['test1', 'test2'], dtype = str)
#eLab_sample_ID = np.array(['test1', 'test2'], dtype = str)
mass_sample =  np.array(['0', '1'], dtype = float)
volume_digestion = np.array(['0', '1'], dtype = float)
conc = np.array(['0', '1'], dtype = float)
aliquote = np.array(['0', '1'], dtype = float)
volume_dilution = np.array(['0', '1'], dtype = float)
conc_dilution = np.array(['0', '1'], dtype = float)
dilution_factor = np.array(['0', '1'], dtype = float)






Step4_table = dilution_input(dilution_ID, initial_sample_ID, eLab_sample_ID, mass_sample,volume_digestion, conc,
                   aliquote, volume_dilution, conc_dilution, dilution_factor)

Step4_table

NameError: name 'initial_sample_ID' is not defined

### STEP 5: Step 5: Remove any negative concentration values or any concentration values that have a std dev that is >30%

Trim Down the table to remove uninteded Values

### STEP 6 Unit Conversion to Mass Percent 

mass % = (conc.sample(mg/l)) * (1kg / 1000g) * (1 mol[ELEMENT]) / (molar mass of [ElEMENT]) * 1mol[ELEMENT] / 1mol[ELEMNT] * 1g/1000mg * molar mass[ELEMENT]/1mol insert comppound or element

### Step 7 


# Possibly plotting graphs, fitting points onto functions for elemental analysis, and exporting the graph in excel format for ease of access